// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iwbhaogdzrwxvappseje.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml3Ymhhb2dkenJ3eHZhcHBzZWplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MDc0NjYsImV4cCI6MjA3MjM4MzQ2Nn0.NNXKPBNzyvAJT6JBR-kVuWx4SpSRnCl841Ez2zNjJlQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});